# * Template for Auto Publish Release with all parameters
# ! You will definitely need to remove some of parameters to make it work

name: Publish Release

# * Trigger (Release new Version) on every Push to main
on:
  push:
    branches:
      - main

jobs:
  main:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Release
        # * In case you really want to use this, using '@main' is not recommended
        # * as breaking change can be made at anytime
        uses: Leomotors/auto-publish-release@main
        with:
          # * GitHub Token, This is REQUIRED and is the only required parameter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # * Default Title is "Release {VERSION}" Pass this parameter to override that
          RELEASE_TITLE: "Auto Publish Release {VERSION}"

          # * Default is either empty, or from CHANGELOG.md if exists, pass this parameter to override
          CHANGELOG_BODY: "Published at {DATE}"

          # * Workflow fail if version does not *change*
          # * Algorithm to compare version isn't implemented yet
          VERSION_MUST_INCREASE: true

          # * Pass github.event.commits[0].message to this parameter to activate the feature, once activated, only commit message consists of [RELEASE] will be considered
          RELEASE_ON_KEYWORD: ${{ github.event.commits[0].message }}

          # * Set to true to allow versions like 0.1.0 to be full release
          LEADING_ZERO_IS_RELEASE: false
