name: Publish Release by Looking at package.json (is this name unique enough?)
author: Leomotors
description: Publish New Release by Looking at package.json

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
  CHANGELOG_BODY:
    description: "Changelog Body when CHANGELOG.md doesn't exist"
  RELEASE_TITLE:
    description: "Override Changelog Title"
  VERSION_SOURCE:
    description: "Where to get Version"
  VERSION_MAJOR_MINOR:
    description: "This must be given if VERSION_SOURCE is COMMIT_COUNT"
  VERSION_MUST_INCREASE:
    description: "Set Check as failed if version doesn't increase"

runs:
  using: "node12"
  main: "index.js"
