name: Publish Release by Looking at package.json (is this name unique enough?)
author: Leomotors
description: Create New Release by looking at package.json

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
  RELEASE_TITLE:
    description: "Override Changelog Title"
  CHANGELOG_BODY:
    description: "Changelog Body when CHANGELOG.md doesn't exist"
  VERSION_SOURCE:
    description: "Where to get Version"
  VERSION_MAJOR_MINOR:
    description: "This must be given if VERSION_SOURCE is COMMIT_COUNT"
  VERSION_MUST_INCREASE:
    description: "Set Check as failed if version doesn't increase"
  RELEASE_ON_KEYWORD:
    description: "Pass github.event.head_commit.message to this parameter to activate the feature, once activated, only commit message consists of [RELEASE] will be considered"
  ALWAYS_GENERATE_NOTES:
    description: "When set to true, always generate release notes (by GitHub)"
  LEADING_ZERO_IS_RELEASE:
    description: "When set to true, version with leading zero (without pre-release keywords) is considered as release"

runs:
  using: "node16"
  main: "index.js"
