name: Publish Release by Looking at package.json (is this name unique enough?)
author: Leomotors
description: Publish New Release by Looking at package.json

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
  PROJECT_NAME:
    description: "Name of Project"

runs:
  using: "node12"
  pre: "setup.js"
  main: "index.js"
