name: Publish Release by Looking at package.json (is this name unique enough?)
author: Leomotors
description: Publish New Release by Looking at package.json

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true

runs:
  using: "node12"
  main: "index.js"
