name: Publish Release by Looking at package.json (is this name unique enough?)
author: Leomotors
description: Create New Release by looking at package.json

inputs:
  githubToken:
    description: "Pass secrets.GITHUB_TOKEN to this"
    required: true
  tag:
    description: "Pass github.ref to this"
  title:
    description: "Title of Release"
  zeroIsPreRelease:
    description: "Mark version leading with zero to be pre-release"
    default: false
  changelog:
    description: "Path of Changelog md file"
    default: "CHANGELOG.md"

  testMode:
    description: "Print the body of REST POST body but not sending it"
    default: false

runs:
  using: "node20"
  main: "dist/index.js"
